create extension if not exists "pgcrypto";
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,name text,created_at timestamptz default now());
create table if not exists public.transactions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,type text not null check(type in('income','expense')),category text not null,description text not null,amount numeric(12,2) not null check(amount>0),date date not null default current_date,payment_method text,created_at timestamptz default now());
create table if not exists public.goals(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,target_amount numeric(12,2) not null check(target_amount>0),current_amount numeric(12,2) not null default 0 check(current_amount>=0),created_at timestamptz default now());
alter table public.profiles enable row level security; alter table public.transactions enable row level security; alter table public.goals enable row level security;
drop policy if exists profiles_select on public.profiles; create policy profiles_select on public.profiles for select using(auth.uid()=id);
drop policy if exists profiles_insert on public.profiles; create policy profiles_insert on public.profiles for insert with check(auth.uid()=id);
drop policy if exists profiles_update on public.profiles; create policy profiles_update on public.profiles for update using(auth.uid()=id) with check(auth.uid()=id);
drop policy if exists tx_select on public.transactions; create policy tx_select on public.transactions for select using(auth.uid()=user_id);
drop policy if exists tx_insert on public.transactions; create policy tx_insert on public.transactions for insert with check(auth.uid()=user_id);
drop policy if exists tx_update on public.transactions; create policy tx_update on public.transactions for update using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists tx_delete on public.transactions; create policy tx_delete on public.transactions for delete using(auth.uid()=user_id);
drop policy if exists goals_select on public.goals; create policy goals_select on public.goals for select using(auth.uid()=user_id);
drop policy if exists goals_insert on public.goals; create policy goals_insert on public.goals for insert with check(auth.uid()=user_id);
drop policy if exists goals_update on public.goals; create policy goals_update on public.goals for update using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists goals_delete on public.goals; create policy goals_delete on public.goals for delete using(auth.uid()=user_id);
